name: flutter_flux
version: 4.0.0
description: Flux library for Flutter, featuring unidirectional dataflow inspired by reflux and Facebook's flux architecture.
homepage: https://github.com/flutter/flutter_flux
dependencies:
  meta: ^1.0.3
  flutter:
   sdk: flutter

dev_dependencies:
  quiver:  ^0.22.0
  rate_limit: ^0.1.0
  test: ^0.12.13

environment:
  sdk: ^1.19.0
